name: CallistoLab-env
channels:
  - conda-forge
dependencies:
- qgrid
- appmode
- bqplot
- scikit-learn
- scipy
- numpy
- pip
- matplotlib
- ipywidgets
- pandas
- ipysheet
- pip:
  - fileupload
  - jupyterlab_latex