#!/bin/bash
jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable python-markdown/main

# Add the fileupload module.
jupyter nbextension install --user --py fileupload
jupyter nbextension enable  --user --py fileupload

# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
jupyter trust CallistoLab-Lite.ipynb

# run matplotlib once to generate the font cache
python3 -c "import os; os.environ["OPENBLAS_CORETYPE"] = "nehalem"; import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"
	
test -e test.png && rm test.png

#jupyter labextension install @jupyterlab/latex
#jupyter lab build